name: Clang-Format Check

on: [push, pull_request]

jobs:
    format-check:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up clang-format
              run: sudo apt-get install -y clang-format

            - name: Run format check
              run: ./tests/clang-format.sh .
